apiVersion: v1
kind: Service
metadata:
  name: rmu-api-attack-tables-service
spec:
  selector:
    app: rmu-api-attack-tables
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3005
  type: ClusterIP
